env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  object-curly-newline: ["error", {
        "ObjectExpression": "always",
        "ObjectPattern": { "multiline": true, "minProperties": 3 },
        "ImportDeclaration": "never",
        "ExportDeclaration": "never"
    }]
  max-len: ["error", { "code": 100 }]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]